name: Update Production Branch

on:
  push:
    branches:
      - development
    paths:
      - '**.js'
      - '**.css'
      - '**.html'
      - 'scripts/**'
      - '.github/workflows/**'

jobs:
  update-production:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout development branch
        uses: actions/checkout@v2
        with:
          ref: development
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install minification tools
        run: |
          npm install -g terser clean-css-cli html-minifier

      - name: Run minification
        run: |
          # Create dist directory
          mkdir -p dist
          
          # Minify JavaScript files
          find . -type f -name "*.js" ! -path "./node_modules/*" ! -path "./dist/*" -exec bash -c '
            mkdir -p dist/$(dirname "{}")
            terser "{}" -o "dist/{}" -c -m
          ' \;
          
          # Minify CSS files
          find . -type f -name "*.css" ! -path "./node_modules/*" ! -path "./dist/*" -exec bash -c '
            mkdir -p dist/$(dirname "{}")
            cleancss -o "dist/{}" "{}"
          ' \;
          
          # Minify HTML files
          find . -type f -name "*.html" ! -path "./node_modules/*" ! -path "./dist/*" -exec bash -c '
            mkdir -p dist/$(dirname "{}")
            html-minifier --collapse-whitespace --remove-comments --remove-optional-tags \
              --remove-redundant-attributes --remove-script-type-attributes \
              --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true \
              "{}" -o "dist/{}"
          ' \;

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or update production branch
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          # Copy minified files from dist to their original locations
          cp -r dist/* .
          rm -rf dist
          
          # Stage all changes
          git add -A
          git commit -m "Minify assets and update production branch"
          
          # Switch to production branch
          git checkout -B production
          
          # Remove development-only files and directories
          git rm -r .github scripts
          git commit -m "Update production branch"
          
          # Push to production branch
          git push https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git production --force

      - name: Cleanup
        if: always()
        run: |
          rm -rf dist
          git checkout development